# development
system:
  # url前缀
  url-path-prefix: api
  # gin模式 debug|release
  app-mode: debug
  # 操作日志key
  operation-log-key: operlog_response
  # 服务端密钥长度必须是16、24、32位字符串其中一种
  key: NxD3S0yuCc9udD6D
  # 程序监听端口
  port: 9000

mysql:
  # 用户名
  username: anew
  # 密码
  password: fabao123
  # 数据库名
  database: anew_db
  # 主机地址
  host: 112.74.50.144
  # 端口
  port: 3466
  # 连接字符串查询参数
  query: charset=utf8&parseTime=True&loc=Local&timeout=10000ms
  # 是否打印SQL日志
  log-mode: true
  # 数据库表前缀
  table-prefix: tb
  # 编码方式
  charset: utf8mb4
  # 字符集
  collation: utf8mb4_general_ci

redis:
  # 地址
  host: 120.77.180.152
  # 密码
  password: fabao123
  # 数据库index
  db: 0
  # 端口
  port: 36379

# casbin配置
casbin:
  # 模型配置文件, 默认以conf目录为根目录
  model-path: 'rbac_model.conf'
  # 自动加载策略延迟（秒）
  load-delay: 60

logs:
  # 日志等级(-1:Debug, 0:Info, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: true

# jwt配置
jwt:
  # jwt标识
  realm: anew
  # token过期时间, 小时
  timeout: 4
  # token更新时间, 小时
  max-refresh: 4

# 上传配置
upload:
  # 上传文件保存路径
  save-dir: upload
  # 单个文件或分片文件最大限制, 单位MB(上传文件先读取到内存, 如果这个值设置过大会导致内存崩溃)
  single-max-size: 32
